
import React, { useState, useEffect } from 'react';
import { Lead, OutreachChannel, OutreachMode } from '../../types';
import { outreachService } from '../../services/outreachService';

interface OutreachModalProps {
  isOpen: boolean;
  onClose: () => void;
  dossier: any;
  lead: Lead;
  onUpdateLead: (id: string, updates: Partial<Lead>) => void;
  onSent?: () => void;
}

export const OutreachModal: React.FC<OutreachModalProps> = ({ isOpen, onClose, dossier, lead, onUpdateLead, onSent }) => {
  if (!isOpen) return null;

  const emailData = dossier.data.outreach?.emailSequence?.[0] || { subject: "Opportunity", body: "Hi there..." };
  const linkedinData = dossier.data.outreach?.linkedin || "Hi, I'd like to connect.";
  
  const [subject, setSubject] = useState(emailData.subject);
  const [body, setBody] = useState(emailData.body);
  const [channel, setChannel] = useState<'GMAIL' | 'LINKEDIN'>('GMAIL');
  const [isSending, setIsSending] = useState(false);

  // Phase 2: Enhanced State
  const [previewMode, setPreviewMode] = useState<'TEXT' | 'HTML'>('TEXT');
  const [sendMode, setSendMode] = useState<'LIVE' | 'TEST'>('LIVE');
  const [adminEmail, setAdminEmail] = useState(() => localStorage.getItem('pomelli_admin_email') || 'admin@pomelli.agency');
  const [uiNotice, setUiNotice] = useState<string | null>(null);
  const [inlineError, setInlineError] = useState<string | null>(null);

  // Persist admin email preference
  useEffect(() => {
    localStorage.setItem('pomelli_admin_email', adminEmail);
  }, [adminEmail]);

  // Switch content based on channel
  const handleChannelSwitch = (c: 'GMAIL' | 'LINKEDIN') => {
    setChannel(c);
    if (c === 'GMAIL') {
      setSubject(emailData.subject);
      setBody(emailData.body);
    } else {
      setSubject("LinkedIn Note");
      setBody(linkedinData);
    }
  };

  const escapeHtml = (s: string) =>
    (s || "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");

  const getHtmlPreview = () => {
    const safeSubject = escapeHtml(subject);
    const safeBody = escapeHtml(body).replace(/\n/g, "<br/>");
    
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8" />
        <title>${safeSubject}</title>
      </head>
      <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; padding: 20px; color: #1e293b; line-height: 1.6; background-color: #ffffff;">
        <div style="max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden;">
          <div style="background: #f8fafc; padding: 12px 20px; border-bottom: 1px solid #e2e8f0;">
             <h2 style="font-size: 16px; font-weight: 700; margin: 0; color: #0f172a;">${safeSubject}</h2>
          </div>
          <div style="padding: 20px; font-size: 14px; color: #334155;">${safeBody}</div>
          <div style="background: #f8fafc; padding: 12px 20px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.1em;">
            Generated by Pomelli Intelligence
          </div>
        </div>
      </body>
      </html>
    `;
  };

  const handleCopyHtml = async () => {
    setInlineError(null);
    await outreachService.copyToClipboard(getHtmlPreview());
    setUiNotice("HTML copied to clipboard.");
    setTimeout(() => setUiNotice(null), 3000);
  };

  const handleSendToMyself = async () => {
    setInlineError(null);
    setUiNotice(null);

    if (!adminEmail || !adminEmail.includes('@')) {
      setInlineError("Please configure a valid Admin Email in TEST mode first.");
      setSendMode('TEST'); // Auto switch to test mode to show input
      return;
    }
    
    setIsSending(true);
    
    const { url, isTruncated } = outreachService.generateMailto({
      to: adminEmail,
      subject: `[TEST] ${subject}`,
      body: body
    });
    
    if (isTruncated) {
      await outreachService.copyToClipboard(body);
      setUiNotice("Body too long. Full text copied to clipboard.");
    }

    window.open(url, '_blank');

    // STRICT RULES: Mode = test, Channel = email, NO status update
    outreachService.logInteraction({
      leadId: lead.id,
      channel: 'email', 
      mode: 'test',
      to: adminEmail,
      subject: `[TEST] ${subject}`,
      body: body
    });
    
    await new Promise(r => setTimeout(r, 600));
    setIsSending(false);
  };

  const handleLaunch = async () => {
    setIsSending(true);
    setUiNotice(null);
    setInlineError(null);
    
    // Determine Recipient
    const targetEmail = sendMode === 'TEST' ? adminEmail : (lead.email || '');
    
    // 1. Trigger the native client
    if (channel === 'GMAIL') {
      const { url, isTruncated } = outreachService.generateMailto({
        to: targetEmail,
        subject,
        body
      });
      
      if (isTruncated) {
        await outreachService.copyToClipboard(body);
        setUiNotice("Body too long. Full text copied to clipboard.");
      }
      
      window.open(url, '_blank');
    } else {
      // For LinkedIn, we copy to clipboard and attempt to open URL
      await outreachService.copyToClipboard(body);
      const targetUrl = lead.contactUrl || lead.websiteUrl;
      window.open(targetUrl, '_blank');
      setUiNotice("Message copied. Opening target...");
    }

    // 2. Log Interaction with STRICT Types
    const logChannel: OutreachChannel = channel === 'GMAIL' ? 'email' : 'linkedin';
    const logMode: OutreachMode = sendMode === 'TEST' ? 'test' : 'live';
    
    const log = outreachService.logInteraction({
      leadId: lead.id,
      channel: logChannel,
      mode: logMode,
      to: targetEmail,
      subject: subject,
      body: body
    });
    
    // 3. Update Lead Status (System of Record) - ONLY IF LIVE
    if (logMode === 'live') {
        const newHistory = [log, ...(lead.outreachHistory || [])];
        
        onUpdateLead(lead.id, {
          outreachStatus: 'sent',
          status: 'sent', // Legacy sync
          lastContactAt: Date.now(),
          outreachHistory: newHistory,
          nextFollowUpAt: Date.now() + (3 * 24 * 60 * 60 * 1000) // +3 days
        });
    }

    // Simulate brief processing for UX
    await new Promise(r => setTimeout(r, 600));
    
    setIsSending(false);
    if (onSent) onSent();
    // Don't close immediately on test so user can iterate
    if (logMode === 'live') onClose();
  };

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-slate-950/80 backdrop-blur-md" onClick={onClose}></div>
      <div className="relative w-full max-w-5xl bg-[#0b1021] border border-slate-800 rounded-[32px] shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200 flex flex-col md:flex-row h-[80vh] md:h-auto md:max-h-[85vh]">
        
        {/* Left: Configuration */}
        <div className="flex-1 flex flex-col border-r border-slate-800 overflow-hidden">
            {/* Header */}
            <div className="p-8 border-b border-slate-800 bg-slate-900/50">
              <h2 className="text-2xl font-black italic text-white uppercase tracking-tighter">CAMPAIGN <span className="text-emerald-500">PRE-FLIGHT</span></h2>
              <p className="text-[10px] font-bold text-slate-500 uppercase tracking-[0.2em] mt-1">Target: {lead.businessName} ({lead.email || 'NO_EMAIL'})</p>
            </div>

            <div className="p-8 space-y-6 flex-1 overflow-y-auto custom-scrollbar">
               {/* Channel Selector */}
               <div className="flex gap-2">
                 <button 
                   onClick={() => handleChannelSwitch('GMAIL')}
                   className={`flex-1 py-3 rounded-xl text-[9px] font-black uppercase tracking-widest border transition-all ${channel === 'GMAIL' ? 'bg-emerald-600 text-white border-emerald-500' : 'bg-slate-900 text-slate-500 border-slate-800'}`}
                 >
                   GMAIL
                 </button>
                 <button 
                   onClick={() => handleChannelSwitch('LINKEDIN')}
                   className={`flex-1 py-3 rounded-xl text-[9px] font-black uppercase tracking-widest border transition-all ${channel === 'LINKEDIN' ? 'bg-emerald-600 text-white border-emerald-500' : 'bg-slate-900 text-slate-500 border-slate-800'}`}
                 >
                   LINKEDIN
                 </button>
                 
                 {channel === 'GMAIL' && (
                   <button 
                     onClick={handleSendToMyself}
                     className="px-4 py-3 rounded-xl text-[9px] font-black uppercase tracking-widest border border-slate-700 bg-slate-800 text-slate-300 hover:text-white hover:bg-slate-700 transition-all flex items-center gap-2"
                     title="Send quick test to Admin Email"
                   >
                     <span>🧪</span> ME
                   </button>
                 )}
               </div>

               {/* Editor Inputs */}
               <div className="space-y-4">
                  <div className="space-y-2">
                     <label className="text-[9px] font-black text-slate-500 uppercase tracking-widest ml-1">Subject Line</label>
                     <input 
                       value={subject}
                       onChange={(e) => setSubject(e.target.value)}
                       className="w-full bg-[#020617] border border-slate-800 rounded-xl px-4 py-3 text-sm font-bold text-white focus:outline-none focus:border-emerald-500 transition-colors"
                     />
                  </div>
                  <div className="space-y-2 flex-1 flex flex-col">
                     <label className="text-[9px] font-black text-slate-500 uppercase tracking-widest ml-1">Message Body</label>
                     <textarea 
                       value={body}
                       onChange={(e) => setBody(e.target.value)}
                       className="w-full bg-[#020617] border border-slate-800 rounded-xl p-4 text-sm font-medium text-slate-300 focus:outline-none focus:border-emerald-500 h-64 resize-none leading-relaxed custom-scrollbar flex-1"
                     />
                  </div>
               </div>
            </div>
        </div>

        {/* Right: Preview & Launch */}
        <div className="w-full md:w-96 bg-slate-900/50 flex flex-col border-l border-slate-800">
            <div className="p-6 border-b border-slate-800 space-y-4">
               <div className="space-y-2">
                  <div className="flex justify-between items-center">
                    <label className="text-[9px] font-black text-slate-500 uppercase tracking-widest">SEND MODE</label>
                    <label className="text-[9px] font-black text-slate-500 uppercase tracking-widest">
                        {sendMode === 'TEST' ? 'ADMIN_EMAIL' : 'TARGET_EMAIL'}
                    </label>
                  </div>
                  <div className="flex bg-slate-950 rounded-lg p-1 border border-slate-800">
                     <button 
                       onClick={() => setSendMode('LIVE')}
                       className={`flex-1 py-2 rounded-md text-[9px] font-black uppercase tracking-widest transition-all ${sendMode === 'LIVE' ? 'bg-emerald-600 text-white shadow-lg' : 'text-slate-500 hover:text-slate-300'}`}
                     >
                       LIVE
                     </button>
                     <button 
                       onClick={() => setSendMode('TEST')}
                       className={`flex-1 py-2 rounded-md text-[9px] font-black uppercase tracking-widest transition-all ${sendMode === 'TEST' ? 'bg-emerald-600 text-white shadow-lg' : 'text-slate-500 hover:text-slate-300'}`}
                     >
                       TEST
                     </button>
                  </div>
               </div>

               {sendMode === 'TEST' && (
                 <div className="space-y-2 animate-in slide-in-from-top-2">
                    <input 
                      value={adminEmail}
                      onChange={(e) => setAdminEmail(e.target.value)}
                      className="w-full bg-slate-950 border border-emerald-500/30 rounded-lg px-3 py-2 text-xs text-emerald-100 focus:outline-none focus:border-emerald-500 placeholder-slate-700"
                      placeholder="admin@agency.com"
                    />
                 </div>
               )}
            </div>

            <div className="flex-1 p-6 space-y-4 overflow-hidden flex flex-col">
               <div className="flex justify-between items-center">
                  <h3 className="text-[9px] font-black text-slate-500 uppercase tracking-widest">PAYLOAD PREVIEW</h3>
                  <div className="flex gap-2">
                     <button 
                       onClick={() => setPreviewMode(previewMode === 'TEXT' ? 'HTML' : 'TEXT')}
                       className="text-[9px] font-black text-emerald-400 hover:text-white uppercase tracking-widest transition-colors"
                     >
                       {previewMode === 'TEXT' ? 'SHOW HTML' : 'SHOW TEXT'}
                     </button>
                     {previewMode === 'HTML' && (
                       <button onClick={handleCopyHtml} className="text-[9px] font-black text-slate-500 hover:text-white uppercase tracking-widest transition-colors">
                         COPY
                       </button>
                     )}
                  </div>
               </div>

               {previewMode === 'TEXT' ? (
                 <div className="space-y-3 text-xs overflow-y-auto custom-scrollbar flex-1">
                    <div className="space-y-1">
                       <span className="text-[8px] font-bold text-slate-600 uppercase">RECIPIENT</span>
                       <p className="font-mono text-slate-300 truncate bg-slate-950 px-2 py-1 rounded border border-slate-800">
                         {sendMode === 'TEST' ? adminEmail : (lead.email || 'NO_EMAIL')}
                       </p>
                    </div>
                    <div className="space-y-1">
                       <span className="text-[8px] font-bold text-slate-600 uppercase">SUBJECT</span>
                       <p className="font-medium text-slate-300 truncate">{subject}</p>
                    </div>
                    <div className="space-y-1">
                       <span className="text-[8px] font-bold text-slate-600 uppercase">BODY SNIPPET</span>
                       <p className="text-slate-400 italic whitespace-pre-wrap border-l-2 border-slate-700 pl-2">
                         {body}
                       </p>
                    </div>
                 </div>
               ) : (
                 <div className="flex-1 bg-white rounded-xl overflow-hidden border border-slate-700">
                    <iframe 
                      srcDoc={getHtmlPreview()} 
                      className="w-full h-full" 
                      sandbox="allow-same-origin"
                      title="Email Preview"
                    />
                 </div>
               )}
            </div>

            <div className="p-6 border-t border-slate-800 space-y-3 bg-slate-900 relative">
               {inlineError && (
                 <div className="text-[9px] text-red-400 font-bold text-center animate-pulse">
                   {inlineError}
                 </div>
               )}
               {uiNotice && (
                 <div className="absolute top-0 left-0 right-0 -mt-10 px-6">
                    <div className="bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-[10px] font-bold py-2 px-3 rounded-lg text-center animate-in slide-in-from-bottom-2 fade-in">
                       {uiNotice}
                    </div>
                 </div>
               )}
               <button 
                 onClick={handleLaunch}
                 disabled={isSending}
                 className={`w-full py-4 rounded-xl text-[10px] font-black uppercase tracking-[0.2em] shadow-xl active:scale-95 transition-all flex items-center justify-center gap-3 disabled:opacity-50 ${
                   sendMode === 'LIVE' 
                     ? 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-emerald-600/20' 
                     : 'bg-emerald-500 hover:bg-emerald-400 text-black shadow-emerald-500/20'
                 }`}
               >
                 {isSending ? (
                    <>
                      <div className={`w-3 h-3 border-2 border-t-transparent rounded-full animate-spin ${sendMode === 'LIVE' ? 'border-white' : 'border-black'}`}></div>
                      <span>LOGGING...</span>
                    </>
                 ) : (
                    <>
                      <span>🚀</span> {sendMode === 'LIVE' ? 'LAUNCH LIVE' : 'SEND TEST'}
                    </>
                 )}
               </button>
               <button onClick={onClose} className="w-full py-3 text-[9px] font-black text-slate-500 hover:text-white uppercase tracking-widest transition-colors">
                 CANCEL FLIGHT
               </button>
            </div>
        </div>

      </div>
    </div>
  );
};
